project_id = "mmopqtoxstnbabavsics"

[functions.send-whatsapp]
verify_jwt = true

[functions.send-game-summary]
verify_jwt = true

[functions.send-pre-match-report]
verify_jwt = true

[functions.receive-whatsapp]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.generate-pre-game-schedule]
verify_jwt = true